const products = [
  /* ---------- 1. SHAMPOO ---------- */
  {
    id: "bain-chroma-respect",
    folder: "shampoo",
    name: "Kerastase Bain Chroma Respect - Shampoo Rambut Diwarnai",
    size: "250 ml",
    price: 588000,
    concern: "colored",
    desc: "Kérastase Bain Chroma Respect adalah sampo bertekstur gel yang berfungsi untuk menghidrasi, memperkuat, dan menjaga ketahanan warna pada rambut yang diwarnai dengan helaian tipis hingga normal.",
    benefits: [
      "Menjaga Warna: Melindungi warna rambut agar tidak mudah pudar dan membuatnya 92% lebih tahan lama.",
      "Menghidrasi: Memberikan kelembapan mendalam pada serat rambut yang kering akibat proses pewarnaan.",
      "Mengurangi Porositas: Menurunkan tingkat porositas rambut agar serat rambut kembali kuat dan tidak mudah patah.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-chronologiste",
    folder: "shampoo",
    name: "Kerastase Chronologiste Regenerant - Shampoo Anti Aging",
    size: "250 ml",
    price: 665000,
    concern: "damaged",
    desc: "Kerastase Chronologiste Bain Régénant adalah sampo anti-aging mewah yang berfungsi untuk membersihkan kulit kepala sekaligus meregenerasi, menghidrasi, dan merevitalisasi kulit kepala serta batang rambut yang rapuh, kusam, dan menipis.",
    benefits: [
      "Membersihkan dan Merevitalisasi: Mengangkat kotoran dan minyak dari kulit kepala secara menyeluruh tanpa membuat rambut menjadi berat atau lepek.",
      "Perawatan Anti-Aging Kulit Kepala: Memperbaiki, melindungi, dan menghidrasi kulit kepala yang kaku, kering, atau kendur akibat tanda-tanda penuaan.",
      "Menutrisi Batang Rambut: Mengembalikan kilau, kelembutan, dan kekuatan pada rambut yang kusam, rapuh, serta kehilangan densitas.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-creme",
    folder: "shampoo",
    name: "Kerastase Bain Crème - Shampoo Anti Ketombe (Kering)",
    size: "250 ml",
    price: 588000,
    concern: "dandruff",
    desc: "Kérastase Symbiose Bain Crème adalah sampo anti-ketombe yang dirancang khusus untuk membersihkan dan melembapkan kulit kepala kering yang rentan terhadap ketombe kering.",
    benefits: [
      "Mengurangi Ketombe: Membantu mengurangi ketombe yang terlihat sejak pemakaian ketiga.",
      "Menekan Jamur: Menekan pertumbuhan jamur Malassezia penyebab ketombe.",
      "Mencegah Ketombe Muncul Kembali: Melindungi kulit kepala agar ketombe tidak mudah datang lagi.",
      "Menghidrasi & Melembutkan: Menghidrasi kulit kepala dan batang rambut sehingga terasa lebih lembut.",
      "Memperkuat Pelindung Kulit Kepala: Mempertahankan scalp barrier agar kulit kepala lebih sehat dan kuat.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-curl-manifesto",
    folder: "shampoo",
    name: "Kerastase Bain Curl Manifesto - Shampoo Rambut Keriting",
    size: "250 ml",
    price: 588000,
    concern: "curly",
    desc: "Kerastase Bain Curl Manifesto adalah shampo krim lembut yang berfungsi untuk membersihkan kulit kepala dan rambut keriting, sangat keriting, atau coily secara lembut sambil menjaga kelembapan alami tanpa membuat rambut terasa berat",
    benefits: [
      "Membersihkan dengan Lembut: Mengangkat kotoran dan minyak pada kulit kepala serta batang rambut tanpa membuat rambut menjadi kering.",
      "Menghidrasi Optimal: Memberikan kelembapan mendalam pada rambut ikal dan keriting tanpa memberikan efek berat atau lepek.",
      "Membentuk Definisi Ikal: Membantu menjaga bentuk lekuk ikal rambut agar terlihat lebih indah, bouncy, bervolume, dan mudah diatur.",
    ],

    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-densite-femme",
    folder: "shampoo",
    name: "Kerastase Bain Densité Femme - Shampoo Penumbuh Rambut (Wanita)",
    size: "250 ml",
    price: 588000,
    concern: "thinner",
    desc: "Kerastase Bain Densite Femme adalah sampo khusus wanita untuk membantu menambah kepadatan, ketebalan, dan volume rambut yang mulai menipis.",
    benefits: [
      "Menebalkan dan Memadatkan: Membantu menumbuhkan dan menambah kepadatan setiap helai rambut agar tampak lebih tebal dan tidak lepek.",
      "Mengaktifkan Folikel: Memperkuat serat rambut dan merangsang folikel rambut yang kurang aktif.",
      "Memberi Volume & Elastisitas: Mengembalikan volume alami dan elastisitas rambut sehingga terasa lebih bervolume dan tahan lama.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-densite-homme",
    folder: "shampoo",
    name: "Kerastase Bain Densité Homme - Shampoo Penumbuh Rambut (Pria)",
    size: "250 ml",
    price: 588000,
    concern: "thinner",
    desc: "Kérastase Bain Densite Homme adalah shampoo khusus pria yang berfungsi untuk mencegah penipisan batang rambut dan mengembalikan kepadatan rambut.",
    benefits: [
      "Menambah Kepadatan: Membantu menjadikan rambut yang tampak tipis dan kurang lebat terasa lebih padat.",
      "Mencegah Penipisan: Merawat dan melindungi batang rambut dari risiko penipisan lebih lanjut.",
      "Membersihkan Kulit Kepala: Membersihkan kulit kepala dengan lembut sekaligus menyegarkan dan meningkatkan kualitas kulit kepala sehari-hari.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-divalent",
    folder: "shampoo",
    name: "Kerastase Bain Divalent - Shampoo Kulit Kepala Berminyak",
    size: "250 ml",
    price: 588000,
    concern: "oily",
    desc: "Kerastase Bain Divalent adalah sampo penyeimbang yang diformulasikan khusus untuk merawat kulit kepala berminyak namun tetap menjaga kelembapan pada batang hingga ujung rambut yang kering.",
    benefits: [
      "Mengontrol Minyak: Membersihkan kulit kepala secara menyeluruh dari minyak berlebih tanpa membuat rambut di bagian panjang menjadi kering.",
      "Menutrisi Batang Rambut: Kandungan seperti Glycine dan Vitamin B6 membantu merawat serta menutrisi area rambut yang sensitif atau kering.",
      "Memberikan Volume: Mengangkat kotoran dan minyak di akar rambut sehingga rambut yang lepek tampak lebih bervolume, ringan, dan segar.",
      "Melembutkan: Menjadikan rambut terasa lebih lembut, mudah diatur, dan berkilau alami.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-elixir",
    folder: "shampoo",
    name: "Kerastase Bain Elixir Ultime - Shampoo Rambut Kusam",
    size: "250 ml",
    price: 588000,
    concern: "frizzy",
    desc: "Fungsi utama Kerastase Bain Elixir Ultime adalah membersihkan rambut sekaligus melembapkan dan memberikan kilau alami pada rambut kusam",
    benefits: [
      "Membersihkan secara menyeluruh: Menghilangkan kotoran, sisa residu produk penata rambut, dan partikel polusi dengan busa yang kaya dan ringan.",
      "Memberikan kilau cemerlang: Mengatasi rambut kusam dan menjaga kilau alami rambut agar tampak sehat berkilau.",
      "Menutrisi dan melembapkan: Diperkaya dengan kombinasi minyak bernutrisi (seperti minyak argan, camelia, dan pracaxi) yang membuat rambut sangat lembut dan mudah diatur tanpa terasa berat.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-extentioniste",
    folder: "shampoo",
    name: "Kerastase Bain Extentioniste - Shampoo Rambut Panjang",
    size: "250 ml",
    price: 588000,
    concern: "thinner",
    desc: "Kérastase Bain Extentioniste adalah sampo penguat rambut yang dirancang khusus untuk membantu memanjangkan dan memperkuat helai rambut yang lemah serta rusak..",
    benefits: [
      "Memperkuat Serat Rambut: Mengandung Creatine R (kombinasi kreatin dan asam amino) yang memperbaiki dan memperkuat struktur internal rambut yang lemah atau rapuh.",
      "Menjaga Kesehatan Kulit Kepala: Dilengkapi dengan Taurine (asam amino) untuk merawat dan menyehatkan kulit kepala.",
      "Memperhalus Permukaan Rambut: Membantu memperbaiki kutikula dan permukaan rambut agar terasa lebih halus serta mencegah ujung rambut bercabang.",
      "Mendukung Pertumbuhan Panjang: Membantu mencapai target rambut panjang yang kuat, tidak mudah putus di tengah jalan, bahkan diklaim membantu pertumbuhan hingga 4 cm dalam 3 bulan pada kondisi optimal.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-fluidealiste",
    folder: "shampoo",
    name: "Kerastase Bain Fluidealiste - Shampoo Rambut Kusut (Frizzy)",
    size: "250 ml",
    price: 588000,
    concern: "frizzy",
    desc: "Kérastase Bain Fluidealiste adalah sampo yang dirancang khusus untuk mengatasi rambut yang sulit diatur, mengembang, dan kusut (frizzy).",
    benefits: [
      "Mengatasi Rambut Megar: Memberikan perlindungan anti-frizz yang tahan lama untuk mengontrol rambut mengembang.",
      "Menghaluskan Serat Rambut: Membersihkan kutikula rambut dengan lembut serta mengembalikan kelembutan dan kelenturan rambut.",
      "Membuat Lebih Mudah Diatur: Membantu meluruskan dan memudahkan penataan rambut sehari-hari.",
      "Mempercepat Pengeringan: Membuat proses pengeringan rambut (blow dry) menjadi dua kali lebih cepat.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-force",
    folder: "shampoo",
    name: "Kerastase Bain Force Architecte - Shampoo Rambut Rapuh dan Rusak",
    size: "250 ml",
    price: 535000,
    concern: "damaged",
    desc: "Fungsi utama Kérastase Resistance Bain Force Architecte adalah membersihkan, memperkuat, dan memperbaiki struktur rambut yang rapuh, rusak, atau bercabang dari dalam.",
    benefits: [
      "Memperkuat dari Dalam: Membangun kembali struktur serat rambut yang melemah atau erosi tingkat 1–2.",
      "Mengurangi Patah: Mencegah rambut mudah patah dan mengatasi ujung rambut bercabang (split-ends).",
      "Mengembalikan Elastisitas: Membuat rambut kembali sehat, elastis, lembut, dan tampak lebih padat.",
      "Kandungan Aktif: Dilengkapi dengan Vita-Ciment (kombinasi Pro-Keratin dan Ceramide-R) serta Intra-Cylane untuk rekonstruksi rambut.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-hydra-fortifiant",
    folder: "shampoo",
    name: "Kerastase Bain Hydra Fortifiant - Shampoo Rambut Rontok (normal)",
    size: "250 ml",
    price: 588000,
    concern: "hairfall",
    desc: "Kérastase Genesis Bain Hydra-Fortifiant adalah sampo anti-rontok yang berfungsi untuk membersihkan kulit kepala berminyak sekaligus memperkuat helai rambut tipis agar tidak mudah patah.",
    benefits: [
      "Mengurangi Rontok karena Patah: Memperkuat serat rambut dari akar hingga ujung agar tidak mudah rapuh.",
      "Membersihkan Kulit Kepala: Mengangkat minyak berlebih (sebum), kotoran, dan partikel polusi secara lembut.",
      "Menghidrasi Ringan: Memberikan kelembapan tanpa membuat rambut lepek atau berat.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-hydra-glaze",
    folder: "shampoo",
    name: "Kerastase Bain Hydra Glaze - Shampoo Anti Frizzy",
    size: "250 ml",
    price: 588000,
    concern: "frizzy",
    desc: "Kérastase Gloss Absolu Bain Hydra-Glaze adalah sampo anti-frizz bertekstur gel ringan yang berfungsi membersihkan kotoran, menghidrasi kutikula secara intensif, dan memberikan kilau ekstra tanpa membuat rambut lepek.",
    benefits: [
      "Membersihkan rambut: Mengangkat kotoran dan residu pada rambut secara optimal.",
      "Melawan frizz dan rambut kusut: Menghaluskan rambut yang sulit diatur dan bebas dari kusut (anti-frizz).",
      "Memberikan kilau tinggi: Membuat rambut tampak lebih berkilau alami, halus, dan rapi (glossy).",
      "Menghidrasi kutikula: Mengandung bahan aktif untuk menjaga kelembapan helai dan kutikula rambut yang kering atau kasar.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-nutri-fortifiant",
    folder: "shampoo",
    name: "Kerastase Bain Nutri Fortifiant - Shampoo Rambut Rontok (kering)",
    size: "250 ml",
    price: 588000,
    concern: "hairfall",
    desc: "Kérastase Genesis Bain Nutri-Fortifiant adalah sampo anti-rontok untuk merawat rambut kering, tebal, dan kasar yang rapuh serta mudah patah.",
    benefits: [
      "Mengurangi Kerontokan: Membantu mengurangi rambut rontok dan patah dari batang rambut.",
      "Menutrisi Rambut Kering: Memberikan kelembapan dan nutrisi ekstra untuk jenis rambut yang kering, tebal, atau kasar.",
      "Melembutkan dan Mencegah Kusut: Membersihkan dengan lembut sehingga rambut tidak mudah kusut saat dicuci.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-oleo",
    folder: "shampoo",
    name: "Kerastase Bain Oleo Relax - Shampoo Rambut Kusut (Frizzy)",
    size: "250 ml",
    price: 588000,
    concern: "frizzy",
    desc: "Kerastase Bain Oleo-Relax adalah sampo yang berfungsi untuk melembutkan, mengatasi rambut kusut (frizzy), serta memudahkan pengaturan rambut yang kering dan mengembang.",
    benefits: [
      "Mengontrol Rambut Kusut (Anti-Frizz): Memberikan perlindungan tahan lama terhadap kelembapan udara (bahkan hingga 80% kelembapan) agar rambut tetap rapi seharian.",
      "Menutrisi Mendalam: Membantu menutrisi serat rambut yang kering dan kasar menggunakan teknologi aktif.",
      "Menghaluskan dan Melembutkan: Merapikan kutikula rambut sehingga tekstur rambut terasa lebih kenyal, lembut, dan mudah disisir.",
      "Mengurangi Volume Berlebih: Menenangkan rambut yang mengembang atau ikal agar tampak lebih jatuh dan terkontrol.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-premiere",
    folder: "shampoo",
    name: "Kerastase Bain Premiere - Shampoo Rambut Rusak",
    size: "250 ml",
    price: 588000,
    concern: "damage",
    desc: "Kérastase Bain Première adalah shampoo untuk membersihkan kulit kepala dan rambut secara lembut sekaligus meluruhkan penumpukan zat kapur (kalsium) berlebih yang membuat rambut rusak..",
    benefits: [
      "Meluruhkan kalsium: Mengandung 3% Citric Acid untuk menghilangkan penumpukan zat kapur dan kalsium dari air yang membuat rambut kaku, kusam, dan kering.",
      "Memperbaiki rambut rusak: Mengandung 5% Glycine untuk membantu menyambungkan kembali ikatan keratin yang rusak akibat proses kimia atau styling panas.",
      "Membersihkan dengan lembut: Memiliki formula creamy bebas sulfat yang aman dan nyaman untuk merawat rambut rusak parah, kering, dan bercabang.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-prevention",
    folder: "shampoo",
    name: "Kerastase Bain Prevention - Shampoo Rambut Rontok (hairloss)",
    size: "250 ml",
    price: 588000,
    concern: "hairloss",
    desc: "Kerastase Bain Prevention adalah sampo perawatan khusus untuk membersihkan kulit kepala serta mencegah masalah kerontokan dan penipisan rambut.",
    benefits: [
      "Membersihkan & Merawat: Membersihkan kulit kepala dari kotoran sekaligus merawat kulit kepala yang mengalami masalah penipisan atau risiko rontok.",
      "Melancarkan Sirkulasi: Mengoptimalkan sirkulasi mikro pada kulit kepala agar suplai nutrisi ke akar rambut lebih lancar.",
      "Menyehatkan Folikel: Menghidrasi, meremajakan, dan melindungi folikel rambut untuk memperpanjang usia helai rambut.",
      "Memberi Volume Instan: Memberikan tekstur pada serat rambut sehingga rambut tampak lebih tebal dan bervolume secara langsung.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-purete",
    folder: "shampoo",
    name: "Kerastase Bain Purete - Shampoo Anti Ketombe (basah)",
    size: "250 ml",
    price: 588000,
    concern: "dandruff",
    desc: "Kérastase Bain Pureté Symbiose adalah sampo anti-ketombe yang diformulasikan khusus untuk mengatasi ketombe basah dan kulit kepala berminyak.",
    benefits: [
      "Mengatasi Ketombe: Membersihkan dan mengurangi ketombe yang terlihat sejak pemakaian ketiga.",
      "Menyeimbangkan Minyak: Mengontrol dan menyeimbangkan kadar minyak berlebih di kulit kepala.",
      "Mengeksfoliasi: Mengangkat sel kulit mati dan kotoran penyebab penumpukan.",
      "Menenangkan Kulit Kepala: Mengurangi rasa gatal atau tidak nyaman pada kulit kepala sensitif yang berketombe.",
      "Menambah Volume: Membuat rambut terasa lebih ringan, bervolume, dan tetap bisa bernapas.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-riche-chroma-respect",
    folder: "shampoo",
    name: "Kerastase Bain Riche Chroma Respect - Shampoo Rambut Diwarnai",
    size: "250 ml",
    price: 588000,
    concern: "colored",
    desc: "Kérastase Bain Riche Chroma Respect adalah sampo bebas sulfat yang berfungsi untuk membersihkan, menutrisi secara mendalam, serta melindungi warna rambut agar tidak mudah pudar, khusus untuk jenis rambut sensitif atau rusak dengan ketebalan sedang hingga tebal akibat pewarnaan.",
    benefits: [
      "Melindungi dan Mengawetkan Warna: Membantu menjaga intensitas dan kilau warna rambut agar tidak mudah pudar bahkan hingga 6 minggu.",
      "Menutrisi Secara Mendalam: Memberikan hidrasi dan kelembapan ekstra pada helai rambut yang kasar, kering, atau rusak akibat bahan kimia pewarna.",
      "Mengurangi Kusut dan Menghaluskan: Melembutkan helai rambut dengan cepat serta mengontrol rambut kusut atau frizz tanpa membuat rambut terasa berat.",
      "Menutup dan Merawat Kutikula: Memperkuat batang rambut dan merawat area serat rambut yang rapuh akibat proses pengerjaan warna.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-riche-dermo",
    folder: "shampoo",
    name: "Kerastase Bain Riche Dermo Calm - Shampoo Kulit Kepala Sensitive",
    size: "250 ml",
    price: 588000,
    concern: "sensitive",
    desc: "Kerastase Bain Riche Dermo-Calm adalah sampo khusus untuk membersihkan secara lembut, menenangkan iritasi, dan merawat kulit kepala sensitif yang disertai kondisi rambut kering.",
    benefits: [
      "Menenangkan Kulit Kepala: Meredakan iritasi, kemerahan, dan rasa gatal pada kulit kepala sensitif.",
      "Menutrisi Rambut Kering: Memiliki formula kaya agen kosmetik yang melembapkan dan menyuburkan batang rambut kering agar terasa lembut serta lebih lentur.",
      "Memberikan Efek Segar: Memberikan sensasi relaksasi dan sejuk yang nyaman pada kulit kepala setelah pemakaian.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-satin",
    folder: "shampoo",
    name: "Kerastase Bain Satin - Shampoo Rambut Kering",
    size: "250 ml",
    price: 535000,
    concern: "dry",
    desc: "Kérastase Nutritive Bain Satin adalah shampoo untuk membersihkan secara lembut sekaligus menghidrasi dan menutrisi rambut kering hingga normal agar kembali lembut, sehat, dan berkilau.",
    benefits: [
      "Menghidrasi Mendalam: Mengembalikan kelembapan rambut kering sehingga tidak mudah dehidrasi.",
      "Menutrisi Serat Rambut: Diperkaya dengan kandungan protein nabati (plant-based protein) dan niasinamida untuk menutrisi batang rambut yang rapuh.",
      "Memberikan Efek Ringan (Lightweight): Membersihkan kulit kepala dan rambut secara lembut tanpa membuat helaian rambut terasa berat lepek.",
      "Mengembalikan Kilau & Kelembutan: Membuat rambut tampak lebih sehat, mudah diatur, dan tampak berkilau alami.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-therapiste",
    folder: "shampoo",
    name: "Kerastase Bain Therapiste - Shampoo Rambut Rusak",
    size: "250 ml",
    price: 588000,
    concern: "damaged",
    desc: "Kérastase Bain Thérapiste adalah sampo bertekstur gel-balm yang berfungsi untuk merawat, memperbaiki, dan merekonstruksi serat rambut yang sangat rusak, rapuh, kaku, serta bercabang akibat proses kimia seperti pewarnaan berlebih, bleaching, pengeritingan, atau smoothing.",
    benefits: [
      "Memperbaiki Serat Rambut: Memiliki tekstur unik seperti balsem/jelly yang merawat dan merekonstruksi struktur rambut rusak saat keramas.",
      "Menggantikan Protein yang Hilang: Mengandung teknologi FIBRA-KAP dan asam amino untuk mengisi kembali protein penunjang keratin (KAP) yang hilang agar rambut kembali kuat.",
      "Mengembalikan Elastisitas: Membuat rambut yang kaku, rapuh, dan bercabang menjadi lebih lembut, elastis, serta mudah diatur.",
      "Melindungi Rambut: Menjaga kelembapan sekaligus melindungi rambut dari kerusakan lanjutan akibat penataan panas atau proses kimia.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-ultra-violet",
    folder: "shampoo",
    name: "Kerastase Bain Ultra Violet - Shampoo Rambut Dibleaching",
    size: "250 ml",
    price: 588000,
    concern: "colored",
    desc: "Kerastase Bain Ultra-Violet adalah sampo yang berfungsi untuk menetralkan warna kuning atau tembaga (brassiness) pada rambut yang telah di-bleaching, beruban, atau berwarna pirang dingin (cool blonde).",
    benefits: [
      "Menetralisir Warna Kuning: Mengandung pigmen ungu pekat yang bekerja cepat untuk menghilangkan pantulan warna kuning atau kusam pada rambut terang.",
      "Membersihkan Lembut: Mengangkat kotoran dan partikel polusi dari rambut secara menyeluruh.",
      "Menutrisi dan Melindungi: Diperkaya dengan Asam Hyaluronic (Hyaluronic Acid) untuk mengisi serta melembapkan serat rambut, serta Bunga Edelweiss (Edelweiss Flower) yang kaya antioksidan untuk melindungi rambut dari kerusakan sehari-hari.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-vital",
    folder: "shampoo",
    name: "Kerastase Bain Vital - Kulit Kepala Sensitive",
    size: "250 ml",
    price: 588000,
    concern: "sensitive",
    desc: "Kerastase Bain Vital Dermo-Calm berfungsi untuk membersihkan secara lembut, menenangkan iritasi, serta meredakan kemerahan, gatal, atau perih pada kulit kepala sensitif dengan jenis rambut normal.",
    benefits: [
      "Meredakan Iritasi: Mengatasi rasa gatal, kemerahan, perih, atau radang pada kulit kepala.",
      "Membersihkan Lembut: Memurnikan dan membersihkan kulit kepala secara higienis tanpa memicu iritasi tambahan.",
      "Memberi Kesegaran: Menghidrasi serta memberikan rasa nyaman dan sejuk pada kulit kepala.",
      "Jenis Rambut: Diformulasikan khusus untuk pemilik kondisi kulit kepala sensitif dengan batang rambut normal.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "bain-volume",
    folder: "shampoo",
    name: "Kerastase Bain Volume - Shampoo Penebal Rambut",
    size: "250 ml",
    price: 535000,
    concern: "thinner",
    desc: "Kérastase Bain Volumifique (atau dikenal sebagai Bain Volume) adalah sampo khusus untuk memberikan volume, mengangkat akar rambut, dan menebalkan helai rambut tipis, halus, atau lepek tanpa membuatnya terasa berat.",
    benefits: [
      "Memberi Volume: Mengangkat akar rambut agar tidak lepek dan tampak lebih bervolume secara instan.",
      "Menguatkan Serat Rambut: Mengonsolidasi struktur rambut halus dan rapuh tanpa membuat rambut terasa berat.",
      "Menebalkan Tampilan Helaian: Membuat rambut terasa lebih tebal, ringan, dan mudah diatur.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala basah secara menyeluruh.",
      "Aplikasikan shampo: Tuangkan shampo secukupnya (sekitar ukuran koin atau 2 pump) ke telapak tangan.",
      "Pijat lembut: Ratakan pada kulit kepala dan batang rambut, lalu gosok hingga berbusa sambil dipijat perlahan.",
      "Bilas dan ulangi: Bilas rambut hingga bersih, lalu lakukan keramas untuk kedua kalinya agar kulit kepala dan rambut benar-benar bersih.",
      "Frekuensi: Gunakan secara rutin setiap 2 hingga 3 hari sekali atau sesuaikan dengan kebutuhan",
    ],
  },
  {
    id: "dry-shampoo",
    folder: "shampoo",
    name: "Kerastase Fresh Affair Refreshing Dry Shampoo - Dry Shampoo Rambut Berminyak",
    size: "223 ml",
    price: 600000,
    concern: "oily",
    desc: "Kerastase Fresh Affair Refreshing Dry Shampoo adalah menyerap kelebihan minyak dan kotoran pada kulit kepala serta akar rambut secara instan tanpa perlu dibilas dengan air.",
    benefits: [
      "Menyerap Minyak Berlebih: Mengandung rice starch (tepung beras) bertekstur bubuk halus yang langsung mengangkat minyak pada akar dan kulit kepala.",
      "Memberikan Volume: Membantu mengangkat akar rambut yang rata atau lepek agar tampak lebih bervolume dan segar.",
      "Menjaga Kelembapan: Diformulasikan dengan Vitamin E untuk mencegah kulit kepala serta batang rambut menjadi kering.",
      "Memberikan Keharuman Mewah: Dilengkapi aroma Glossy Neroli karya Fabrice Pellegrin yang memberikan keharuman tahan lama hingga 24 jam.",
      "Nyaman Tanpa Residu: Memberikan sensasi bersih dan ringan tanpa meninggalkan residu putih yang mengganggu penampilan.",
    ],
    howToUse: [
      "Kocok botol secara perlahan sebelum setiap pemakaian.",
      "Beri jarak sekitar 15 cm antara botol semprot dan kepala Anda.",
      "Semprotkan secara merata pada bagian akar rambut dan kulit kepala yang berminyak atau lepek.",
      "Sisir atau pijat dengan lembut menggunakan jari untuk meratakan produk serta membersihkan sisa kelebihan bubuk.",
      "Tidak perlu dibilas, dan produk ini bisa dipakai berulang kali sesuai kebutuhan.",
    ],
  },
  {
    id: "micropeeling",
    folder: "shampoo",
    name: "Kerastase Symbiose Micro-peeling Cellulaire - Pre Shampoo Anti Ketombe",
    size: "200 ml",
    price: 920000,
    concern: "dandruff",
    desc: "Kérastase Symbiose Micro-Peeling Cellulaire 200ml berfungsi sebagai perawatan pre-shampoo untuk mengeksfoliasi kulit kepala sensitif yang berketombe.",
    benefits: [
      "Mengangkat Sel Kulit Mati: Membersihkan tumpukan sel kulit mati dan serpihan putih (ketombe) pada tingkat biologis maupun visual.",
      "Membersihkan Kulit Kepala: Formula Salicylic Acid 1,9% dan butiran scrub halus (dari Argan & Apricot seeds) membersihkan kulit kepala secara menyeluruh tanpa menyebabkan iritasi.",
      "Meredakan Ketidaknyamanan: Membantu mengurangi rasa gatal atau tidak nyaman akibat ketombe pada kulit kepala yang sensitif.",
      "Memberikan Volume dan Kesegaran: Membuat kulit kepala terasa bersih dan segar, menjadikan akar rambut lebih bervolume, serta menjaga rambut tetap lembut.",
    ],
    howToUse: [
      "Basahi rambut: Pastikan rambut dan kulit kepala Anda dalam keadaan basah.",
      "Ambil produk: Tuangkan produk secukupnya (sekitar ukuran biji hazel atau setara 15 ml) ke telapak tangan Anda.",
      "Aplikasikan: Oleskan dan ratakan menggunakan ujung jari pada bagian tengah serta sisi-sisi kulit kepala.",
      "Pijat perlahan: Pijat kulit kepala secara merata dengan gerakan melingkar menggunakan ujung jari untuk memberikan efek eksfoliasi yang lembut.",
      "Emulsikan dan bilas: Tambahkan sedikit air, emulsikan (busakan sebentar), lalu bilas hingga bersih.",
      "Lanjutkan keramas: Setelah dibilas, lanjutkan dengan pemakaian sampo dari rangkaian Kérastase Symbiose (seperti Bain Pureté atau Bain Crème) seperti biasa.",
      "Gunakan 1 hingga 2 kali dalam seminggu sebelum keramas.",
    ],
  },

  /* ---------- 2. FONDANT / CONDITIONER ---------- */
  {
    id: "cau",
    folder: "fondant",
    name: "Kerastase Ciment Anti Usure - Kondisioner Rambut Rusak",
    size: "200 ml",
    price: 665000,
    concern: "damage",
    desc: "Kerastase Ciment Anti-Usure berfungsi sebagai kondisioner perawatan untuk menutup kutikula serta memperbaiki struktur rambut yang rapuh, lemah, dan rusak akibat proses kimia.",
    benefits: [
      "Memperkuat Serat Rambut: Mengembalikan struktur internal dan mengonsolidasi serat rambut yang rapuh atau rusak (level erosi 1-2).",
      "Melindungi dan Menutupi Kutikula: Melapisi permukaan rambut dengan lapisan pelindung anti-agresi serta menjaga ketahanan rambut dari kerusakan harian.",
      " Menjadikan Rambut Lembut: Membuat rambut terasa lebih lembut, ringan, dan tidak mudah patah.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-cica-chroma",
    folder: "fondant",
    name: "Kerastase Fondant Cica Chroma - Kondisioner Rambut Diwarnai",
    size: "200 ml",
    price: 715000,
    concern: "colored",
    desc: "Kérastase Chroma Absolu Fondant Cica Chroma adalah kondisioner anti-porositas bertekstur ringan yang diformulasikan khusus untuk merawat dan memperkuat rambut tipis hingga sedang yang rusak atau sensitif akibat pewarnaan.",
    benefits: [
      "Mengurangi Porositas: Mengisi area serat rambut yang berpori akibat proses pewarnaan atau bleaching.",
      "Memperkuat Batang Rambut: Menguatkan struktur helai rambut dari dalam agar tidak mudah patah atau rapuh.",
      "Melindungi Warna Rambut: Mencegah pigmen warna agar tidak cepat pudar saat dicuci atau terkena proses keramas.",
      "Menghidrasi & Melembutkan: Memberikan kelembapan intensif tanpa membuat rambut terasa lepek atau berat.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-cicaflash",
    folder: "fondant",
    name: "Kerastase Fondant Cicaflash - Kondisioner Rambut Dibleaching",
    size: "250 ml",
    price: 715000,
    concern: "colored",
    desc: "Kérastase Fondant Cicaflash adalah kondisioner perawatan intensif yang berfungsi untuk melembapkan, menguatkan, dan menutrisi rambut yang telah melalui proses bleaching, highlight, atau pewarnaan pirang.",
    benefits: [
      "Menutup Kutikula: Mengunci nutrisi dan merapikan kutikula rambut setelah proses kimia atau bleaching.",
      "Menjaga Warna: Mempertahankan warna rambut pirang atau terang agar tidak mudah pudar akibat proses keramas serta menetralkan pantulan warna kuning/oranye yang tidak diinginkan.",
      "Menguatkan Rambut: Memperkuat serat rambut yang rapuh sehingga rambut menjadi 10x lebih kuat dan tidak mudah patah.",
      "Melembapkan & Melembutkan: Memberikan hidrasi mendalam tanpa membuat rambut lepek, menjadikan rambut lebih mudah disisir, halus, dan berkilau.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-curl-manifesto",
    folder: "fondant",
    name: "Kerastase Fondant Curl Manifesto - Kondisioner Rambut Keriting",
    size: "250 ml",
    price: 715000,
    concern: "curly",
    desc: "Kérastase Fondant Curl Manifesto adalah kondisioner khusus yang berfungsi untuk menghidrasi, melembutkan, dan mengunci kelembapan pada rambut keriting tanpa membuatnya terasa berat.",
    benefits: [
      "Menghidrasi dan Mengunci Kelembapan: Memberikan kelembapan esensial pada rambut keriting dan sangat keriting.",
      "Mengurangi Kusut (Frizz): Mencegah rambut megar dan melawan kelembapan udara hingga 24 jam.",
      "Melembutkan dan Menguraikan Simpul: Membantu mengurai rambut yang kusut dengan lembut dan membuat helai rambut terasa lebih halus serta bouncy.",
      "Menutup Kutikula: Menjaga kesehatan kutikula rambut agar bentuk ikal tampak alami dan rapi.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-densite",
    folder: "fondant",
    name: "Kerastase Fondant Densite - Kondisioner Penebal Rambut",
    size: "200 ml",
    price: 715000,
    concern: "thinner",
    desc: "Kérastase Densifique Fondant Densité 200ml adalah kondisioner ringan yang berfungsi untuk menebalkan, memadatkan, dan memberi volume pada rambut yang tipis atau menipis.",
    benefits: [
      "Menebalkan Rambut: Memberikan tekstur, substansi, dan kepadatan ekstra pada setiap helai rambut agar tampak lebih penuh.",
      "Menambah Volume: Membuat rambut mengembang alami dan bervolume tanpa membuat akar atau batang rambut terasa lepek.",
      "Menguatkan Struktur: Diperkaya dengan Intra-Cylane® untuk memperkuat kerangka serat rambut dari dalam agar tidak mudah patah.",
      "Menghidrasi & Melembutkan: Mengandung Hyaluronic Acid yang mengunci nutrisi serta menjaga kelembapan rambut tipis agar tetap lembut dan mudah diatur.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-elixir",
    folder: "fondant",
    name: "Kerastase Le Fondant Elixir  - Kondisioner Rambut Kusam",
    size: "200 ml",
    price: 715000,
    concern: "frizzy",
    desc: "Kérastase Elixir Ultime Le Fondant adalah kondisioner beresens minyak yang menutrisi, melembutkan, dan membuat rambut kusam tampak lebih berkilau.",
    benefits: [
      "Memberi Kilau Ekstra: Membuat rambut terlihat 7x lebih berkilau seketika.",
      "Menutrisi Mendalam: Memberikan kelembapan dan nutrisi pada serat rambut yang bertahan hingga 48 jam.",
      "Menghaluskan dan Mengatasi Kusut: Mengontrol rambut kusut (frizz) hingga 96 jam serta mempermudah proses menyisir dari akar sampai ujung.",
      "Menguatkan Rambut: Diperkaya campuran minyak (seperti Argan Oil, Camellia, Corn Germ, dan ekstrak Amla) untuk memperkuat helai rambut yang kusam dan normal.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-exten",
    folder: "fondant",
    name: "Kerastase Fondant Extentioniste  - Kondisioner Rambut Panjang",
    size: "200 ml",
    price: 715000,
    concern: "thinner",
    desc: "Kérastase Resistance Fondant Extentioniste adalah kondisioner ringan yang berfungsi untuk memperkuat batang rambut, mencegah rambut patah dan bercabang, serta membantu proses pemanjangan rambut.",
    benefits: [
      "Memperkuat Serat Rambut: Menembus ke dalam struktur rambut untuk meningkatkan kekuatan alami dari akar hingga ujung.",
      "Menutup Kutikula: Melapisi dan meratakan kutikula rambut agar terasa lebih lembut, halus, dan mudah diatur.",
      "Meningkatkan Elastisitas: Mencegah rambut rapuh dan patah sehingga target rambut panjang yang sehat bisa tercapai.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-fluidealiste",
    folder: "fondant",
    name: "Kerastase Fondant Fluidealiste  - Kondisioner Rambut Kusut (Frizzy)",
    size: "200 ml",
    price: 715000,
    concern: "frizzy",
    desc: "Kerastase Fondant Fluidealiste adalah kondisioner ringan yang berfungsi untuk mengatasi rambut kusut, mengembang (frizzy), dan sulit diatur agar tampak lebih halus, lembut, serta mudah ditata tanpa membuatnya terasa berat.",
    benefits: [
      "Mengontrol Frizz: Menutup kutikula rambut dan mencegah rambut mengembang akibat kelembapan.",
      "Menghaluskan & Melembutkan: Memberikan nutrisi dan kelembutan ekstra pada setiap helaian rambut yang sulit diatur.",
      "Mempermudah Penataan: Membuat rambut lebih mudah disisir, lebih lurus alami, serta terasa ringan dan jatuh dengan indah (movement).",
      "Teknologi Morpho-Keratin Complex: Memperkuat serat rambut dan melindungi permukaan rambut dari kelembapan.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-renforcateur",
    folder: "fondant",
    name: "Kerastase Fondant Renforcateur  - Kondisioner Rambut Rontok",
    size: "200 ml",
    price: 715000,
    concern: "hairfall",
    desc: "Kérastase Genesis Fondant Renforcateur adalah kondisioner ringan yang berfungsi untuk memperkuat serat rambut, mengurangi rambut rontok akibat patah, serta menutrisi rambut tanpa membuatnya lepek.",
    benefits: [
      "Mengurangi rambut rontok: Memperkuat ketahanan alami helai rambut agar tidak mudah rapuh dan patah.",
      "Melembutkan dan menghaluskan: Membuat rambut lebih mudah disisir, terasa lembut, serta bebas kusut (frizz).",
      "Menutrisi tanpa membebani: Memberikan perawatan mendalam dengan tekstur krim yang tetap terasa ringan di rambut.",
      "Melindungi kutikula: Menutup dan melindungi kutikula rambut sekaligus memberikan kilau alami.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-insta-glaze",
    folder: "fondant",
    name: "Kerastase Fondant Insta Glaze  - Kondisioner Rambut Kusut (Frizzy)",
    size: "250 ml",
    price: 715000,
    concern: "frizzy",
    desc: "Kérastase Gloss Absolu Fondant Insta Glaze adalah kondisioner rambut yang berfungsi untuk memberikan hidrasi mendalam, mengatasi rambut kusut (anti-frizz), serta menciptakan permukaan rambut yang halus dan berkilau.",
    benefits: [
      "Menghidrasi Batang Rambut: Memberikan kelembapan intensif pada setiap lapisan serat rambut yang kering.",
      "Merapatkan Kutikula (Tighten): Menghaluskan permukaan rambut agar memantulkan cahaya alami dan tampak berkilau.",
      "Mengatasi Rambut Kusut: Mencegah frizz hingga 4 hari serta memudahkan proses penyisiran (detangling).",
      "Melembutkan Tanpa Lepek: Memiliki tekstur krim lembut yang ringan di rambut dan tidak membuatnya terasa berat atau berminyak.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-premiere",
    folder: "fondant",
    name: "Kerastase Fondant Premiere  - Kondisioner Rambut Rusak",
    size: "200 ml",
    price: 715000,
    concern: "damaged",
    desc: "Kérastase Fondant Première (Fondant Fluidité Réparateur) berfungsi sebagai kondisioner bertekstur ringan untuk mendekalsifikasi, menghidrasi, dan memperbaiki rambut rusak dari dalam serta luar.",
    benefits: [
      "Dekalsifikasi (Menghilangkan Penumpukan Kalsium): Membersihkan endapan kalsium dari air sadah yang membuat rambut terasa kaku, keras, dan kusam.",
      "Memperbaiki Rambut Rusak dari Dalam: Mengandung glycine dan asam sitrat yang membantu menembus lapisan dalam serat rambut untuk menyambungkan kembali ikatan keratin yang rusak serta mengembalikan kekuatan rambut.",
      "Mengembalikan Kelembapan & Kelenturan: Menghidrasi secara intensif, mengurangi rambut kaku, serta menjadikan rambut lebih lembut, kenyal, dan mudah diatur tanpa terasa berat.",
      "Meningkatkan Kilau & Ketahanan: Membuat rambut terlihat lebih berkilau, halus, serta tidak mudah patah.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "fondant-symbiose",
    folder: "fondant",
    name: "Kerastase Fondant Symbiose Apaisant  - Kondisioner Rambut Ketombe",
    size: "200 ml",
    price: 715000,
    concern: "dandruff",
    desc: "Kérastase Fondant Symbiose adalah kondisioner ringan yang berfungsi untuk menenangkan kulit kepala sensitif dan merawat rambut yang rentan berketombe.",
    benefits: [
      "Menenangkan Kulit Kepala: Membantu mengurangi rasa gatal, kemerahan, dan rasa tidak nyaman pada kulit kepala sensitif.",
      "Menjaga Penghalang Kulit Kepala (Scalp Barrier): Memperkuat dan mempertahankan pelindung alami kulit kepala dengan kandungan seperti Bifidus dan Salicylic Acid.",
      "Menghidrasi & Melembapkan: Memberikan kelembapan esensial pada kulit kepala dan serat rambut agar tetap lembut dan mudah diatur.",
      "Menutup Kutikula Rambut: Membuat helai rambut tampak lebih berkilau, lembut, dan bervolume secara alami.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },
  {
    id: "lait-vital",
    folder: "fondant",
    name: "Kerastase Lait Vital  - Kondisioner Rambut Kering",
    size: "200 ml",
    price: 635000,
    concern: "dry",
    desc: "Kérastase Nutritive Lait Vital adalah kondisioner bertekstur sangat ringan yang dirancang khusus untuk menutrisi dan melembutkan rambut normal hingga sedikit kering tanpa membuatnya terasa lepek atau berat.",
    benefits: [
      "Menutrisi Rambut Kering: Memberikan kelembapan dan nutrisi intensif hingga ke batang rambut tanpa membuatnya terasa berat.",
      "Melembutkan dan Menghaluskan: Mengembalikan kelembutan alami, kilau, serta menjadikan rambut lebih mudah diatur dan bebas kusut.",
      "Menutup Kutikula: Mengunci nutrisi di dalam serat rambut serta mencegah kekeringan lebih lanjut.",
      "Formula Ringan (Ultra-Lightweight): Meresap mendalam tanpa membuat rambut menjadi lepek, berminyak, atau kehilangan volume alaminya.",
    ],
    howToUse: [
      "Aplikasikan pada batang hingga ujung rambut yang bersih dan setengah basah (dalam kondisi kering handuk) setelah keramas.",
      "Hindari pengaplikasian langsung atau pemijatan pada kulit kepala.",
      "Diamkan selama 2-3 menit, emulsikan dengan sedikit air, lalu bilas hingga benar-benar bersih.",
    ],
  },

  /* ---------- 3. SERUM ---------- */
  {
    id: "8h-90",
    folder: "serum",
    name: "Kerastase Nutritive 8H Magic Night Serum - Serum Rambut Kering",
    size: "90 ml",
    price: 830000,
    concern: "dry",
    desc: "Kérastase 8H Magic Night Serum 90ml adalah serum perawatan tanpa bilas yang bekerja selama 8 jam di malam hari untuk menutrisi, melembapkan, dan melindungi rambut kering dari gesekan bantal saat tidur.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "cicaplasme-150",
    folder: "serum",
    name: "Kerastase Blond Absolu Cicaplasme Serum - Serum Rambut Dibleaching",
    size: "150 ml",
    price: 760000,
    concern: "colored",
    desc: "Kerastase Blond Absolu Cicaplasme 150ml adalah krim leave-in (tanpa bilas) sekaligus heat-protectant serum yang dirancang khusus untuk merawat rambut berwarna pirang (blonde), highlight, atau yang mengalami proses bleaching.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "cure-anti-chute-10",
    folder: "serum",
    name: "Kerastase Genesis Cure Anti-Chute - Serum Rambut Rontok",
    size: "10x6 ml",
    price: 1270000,
    concern: "hairfall",
    desc: "Kérastase Genesis Cure Anti-Chute 10x6ml adalah serum intensif anti-hair fall dalam bentuk ampul untuk merawat kulit kepala dan mengurangi kerontokan rambut dari akar.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "cure-anti-chute-42",
    folder: "serum",
    name: "Kerastase Genesis Cure Anti-Chute - Serum Rambut Rontok",
    size: "42x6 ml",
    price: 4380000,
    concern: "hairfall",
    desc: "Kerastase Genesis Cure Anti-Chute 42x6ml adalah serum atau tonik intensif yang berfungsi untuk mengurangi kerontokan rambut parah dari akar serta mencegah batang rambut patah.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "cure-apaisant-10",
    folder: "serum",
    name: "Kerastase Genesis Cure Apaisant - Serum Kulit Kepala Sensitive",
    size: "10x6 ml",
    price: 1270000,
    concern: "sensitive",
    desc: "Kerastase Cure Apaisante 10x6ml adalah serum atau tonik intensif untuk meredam iritasi, gatal, dan kemerahan pada kulit kepala yang sensitif.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "cure-densite-10",
    folder: "serum",
    name: "Kerastase Densifique Cure Densite - Serum Penumbuh Rambut",
    size: "10x6 ml",
    price: 1270000,
    concern: "thinner",
    desc: "Kérastase Cure Densité 10x6ml adalah serum tonik penumbuh rambut intensif yang berfungsi untuk menambah kepadatan, mempertebal helai rambut, dan merangsang pertumbuhan rambut baru.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "cure-densite-42",
    folder: "serum",
    name: "Kerastase Densifique Cure Densite - Serum Penumbuh Rambut",
    size: "42x6 ml",
    price: 4380000,
    concern: "thinner",
    desc: "Kerastase Cure Densite 42x6ml adalah serum intensif untuk menumbuhkan rambut baru, mempertebal helai rambut, dan mengatasi penipisan.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "curl-manifesto",
    folder: "serum",
    name: "Kerastase Curl Manifesto Creme De Jour Fondamentale - Krim Rambut Keriting",
    size: "150 ml",
    price: 760000,
    concern: "curly",
    desc: "Kerastase Curl Manifesto Crème de Jour Fondamentale adalah krim perawatan tanpa bilas (leave-in treatment) harian yang berfungsi melembapkan, mendefinisikan bentuk ikal, serta melindungi rambut keriting agar tidak kusut dan mengembang (frizz).",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "densifique-homme-30",
    folder: "serum",
    name: "Kerastase Densifique Homme - Serum Penumbuh Rambut (Pria)",
    size: "30x6 ml",
    price: 3850000,
    concern: "thinner",
    desc: "Kérastase Densifique Homme 30x6ml adalah serum penumbuh rambut khusus pria untuk mengatasi rambut menipis dan mengembalikan kepadatan kulit kepala.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "extentioniste-50",
    folder: "serum",
    name: "Kerastase Extentioniste - Serum Rambut Panjang ",
    size: "50 ml",
    price: 680000,
    concern: "thinner",
    desc: "Kérastase Serum Extentioniste 50ml adalah serum konsentrasi tinggi untuk kulit kepala dan batang rambut yang berfungsi memperkuat serat rambut dari akar agar tidak mudah patah dan mendukung pertumbuhan rambut panjang yang sehat.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "genesis-30",
    folder: "serum",
    name: "Kerastase Genesis Anti Hairfall Serum - Serum Rambut Rontok",
    size: "30 ml",
    price: 415000,
    concern: "hairfall",
    desc: "Kerastase Serum Genesis 30ml adalah serum kulit kepala harian yang berfungsi untuk mengurangi rambut rontok dari akar dan mencegah rambut patah dari batang.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "genesis-90",
    folder: "serum",
    name: "Kerastase Genesis Anti Hairfall Serum - Serum Rambut Rontok",
    size: "90 ml",
    price: 830000,
    concern: "hairfall",
    desc: "Kerastase Serum Genesis 90ml berfungsi sebagai serum harian untuk kulit kepala guna mengurangi rambut rontok dari akar dan mencegah patah pada batang rambut.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "potentialiste-30",
    folder: "serum",
    name: "Kerastase Potentialiste Scalp Serum - Serum Keseimbangan Kulit Kepala",
    size: "30 ml",
    price: 415000,
    concern: "sensitive",
    desc: "Kerastase Spécifique Potentialiste Serum berfungsi untuk menyeimbangkan mikrobioma kulit kepala, meredakan gatal, serta melindungi kulit kepala dari polusi dan kerusakan eksternal.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "potentialiste-90",
    folder: "serum",
    name: "Kerastase Potentialiste Scalp Serum - Serum Keseimbangan Kulit Kepala",
    size: "90 ml",
    price: 830000,
    concern: "sensitive",
    desc: "Kérastase Specifique Potentialiste Serum 90ml berfungsi sebagai serum penyeimbang universal untuk menjaga kesehatan mikrobioma dan pertahanan pelindung (barrier) kulit kepala.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "premiere-split-end-30",
    folder: "serum",
    name: "Kerastase Premiere Anti Split Ends Serum - Serum Rambut Rusak",
    size: "30 ml",
    price: 635000,
    concern: "damaged",
    desc: "Kerastase Première Split Ends Serum 30ml berfungsi untuk memperbaiki secara intensif, melapisi, dan menyegel ujung rambut yang bercabang serta rusak akibat proses kimia atau panas.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "soin-acide-210",
    folder: "serum",
    name: "Kerastase Soin Acide Chroma Gloss - Serum Rambut Diwarnai",
    size: "210 ml",
    price: 620000,
    concern: "colored",
    desc: "Kerastase Soin Acide Chroma Gloss 210ml adalah serum bilas (rinsed hair serum) untuk memberikan lapisan kilau ekstra dan menghidrasi rambut yang diwarnai.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "split-end-50",
    folder: "serum",
    name: "Kerastase Nutritive Split Ends Serum - Serum Rambut Kering",
    size: "50 ml",
    price: 588000,
    concern: "dry",
    desc: "Kerastase Nutritive Split Ends Serum 50ml berfungsi sebagai konsentrat penutrisi tinggi untuk menyegel, mencegah, dan mengurangi ujung rambut bercabang sekaligus mengembalikan kelembapan pada ujung rambut yang kering.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "stimuliste",
    folder: "serum",
    name: "Kerastase Specifique Stimuliste - Serum Rambut Rontok ",
    size: "125 ml",
    price: 765000,
    concern: "hairloss",
    desc: "Kerastase Stimuliste 125ml adalah serum kulit kepala harian berbentuk spray yang berfungsi untuk mencegah kerontokan dan memperkuat akar rambut.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "symbiose-30",
    folder: "serum",
    name: "Kerastase Serum Symbiose - Serum Anti Ketombe ",
    size: "30 ml",
    price: 415000,
    concern: "dandruff",
    desc: "Kerastase Serum Symbiose (Sérum Cellulaire Nuit Anti-Pelliculaire Intensif) adalah serum malam intensif untuk mengatasi ketombe basah maupun kering serta menenangkan kulit kepala sensitif.",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "symbiose-90",
    folder: "serum",
    name: "Kerastase Serum Symbiose - Serum Anti Ketombe ",
    size: "90 ml",
    price: 830000,
    concern: "dandruff",
    desc: "Kérastase Serum Symbiose 90ml adalah serum malam intensif anti-ketombe yang berfungsi untuk mengatasi ketombe basah maupun kering, menekan jamur penyebab ketombe, serta menenangkan kulit kepala sensitif selama 8 jam di malam hari.",
    benefits: [""],
    howToUse: [""],
  },

  /* ---------- 3. MASQUE / MASKER ---------- */
  {
    id: "m-argile-250",
    folder: "masque",
    name: "Kerastase Argile Equilibrante Clay - Masker Rambut Berminyak",
    size: "250 ml",
    price: 920000,
    concern: "oily",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-argile-500",
    folder: "masque",
    name: "Kerastase Argile Equilibrante Clay - Masker Rambut Berminyak",
    size: "500 ml",
    price: 1870000,
    concern: "oily",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "masquintense-200",
    folder: "masque",
    name: "Kerastase Nutritive Masquintense - Masker Rambut Kering",
    size: "200 ml",
    price: 840000,
    concern: "dry",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "masquintense-500",
    folder: "masque",
    name: "Kerastase Nutritive Masquintense - Masker Rambut Kering",
    size: "500 ml",
    price: 1760000,
    concern: "dry",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-chromafiller-200",
    folder: "masque",
    name: "Kerastase Masque Chroma Filler - Masker Rambut Diwarnai",
    size: "200 ml",
    price: 920000,
    concern: "colored",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-chromafiller-500",
    folder: "masque",
    name: "Kerastase Masque Chroma Filler - Masker Rambut Diwarnai",
    size: "500 ml",
    price: 1870000,
    concern: "colored",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-chronologiste-200",
    folder: "masque",
    name: "Kerastase Masque Chronologiste Regenerant - Masker Anti Aging",
    size: "200 ml",
    price: 1055000,
    concern: "damaged",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-chronologiste-500",
    folder: "masque",
    name: "Kerastase Masque Chronologiste Regenerant - Masker Anti Aging",
    size: "500 ml",
    price: 2060000,
    concern: "damaged",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-curl-200",
    folder: "masque",
    name: "Kerastase Masque Curl Manifesto - Masker Rambut Keriting & Ikal",
    size: "200 ml",
    price: 920000,
    concern: "curl",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-densite-200",
    folder: "masque",
    name: "Kerastase Masque Densite - Masker Penebal Rambut",
    size: "200 ml",
    price: 920000,
    concern: "thinner",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-densite-500",
    folder: "masque",
    name: "Kerastase Masque Densite - Masker Penebal Rambut",
    size: "500 ml",
    price: 1870000,
    concern: "thinner",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-elixir-200",
    folder: "masque",
    name: "Kerastase Masque Elixir - Masker Rambut Berkilau",
    size: "200 ml",
    price: 920000,
    concern: "frizzy",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-extentioniste-200",
    folder: "masque",
    name: "Kerastase Masque Extentioniste - Masker Rambut Panjang",
    size: "200 ml",
    price: 920000,
    concern: "thinner",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-extentioniste-500",
    folder: "masque",
    name: "Kerastase Masque Extentioniste - Masker Rambut Panjang",
    size: "500 ml",
    price: 1870000,
    concern: "thinner",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-force-200",
    folder: "masque",
    name: "Kerastase Masque Force Architecte - Masker Rambut Rapuh",
    size: "200 ml",
    price: 920000,
    concern: "damaged",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-force-500",
    folder: "masque",
    name: "Kerastase Masque Force Architecte - Masker Rambut Rapuh",
    size: "500 ml",
    price: 1870000,
    concern: "damaged",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-hydra-apaisant-200",
    folder: "masque",
    name: "Kerastase Masque Hydra Apaisant - Masker Kulit Kepala Sensitive",
    size: "200 ml",
    price: 920000,
    concern: "sensitive",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-hydra-apaisant-500",
    folder: "masque",
    name: "Kerastase Masque Hydra Apaisant - Masker Kulit Kepala Sensitive",
    size: "500 ml",
    price: 1870000,
    concern: "sensitive",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-oleo-200",
    folder: "masque",
    name: "Kerastase Masque Oleo Relax - Masker Rammbut Kusut (Frizzy)",
    size: "200 ml",
    price: 920000,
    concern: "frizzy",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-oleo-500",
    folder: "masque",
    name: "Kerastase Masque Oleo Relax - Masker Rammbut Kusut (Frizzy)",
    size: "500 ml",
    price: 1870000,
    concern: "frizzy",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-reconstituant-200",
    folder: "masque",
    name: "Kerastase Masque Reconstituant - Masker Rambut Rontok",
    size: "200 ml",
    price: 920000,
    concern: "hairfall",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-reconstituant-500",
    folder: "masque",
    name: "Kerastase Masque Reconstituant - Masker Rambut Rontok",
    size: "500 ml",
    price: 1870000,
    concern: "hairfall",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-rehydratant-200",
    folder: "masque",
    name: "Kerastase Masque Rehydratant - Masker Rambut Kering",
    size: "200 ml",
    price: 920000,
    concern: "dry",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-rehydratant-500",
    folder: "masque",
    name: "Kerastase Masque Rehydratant - Masker Rambut Kering",
    size: "500 ml",
    price: 1870000,
    concern: "dry",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-symbiose-200",
    folder: "masque",
    name: "Kerastase Masque Symbiose Apaisant - Masker Rambut Ketombe",
    size: "200 ml",
    price: 920000,
    concern: "dandruff",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-symbiose-500",
    folder: "masque",
    name: "Kerastase Masque Symbiose Apaisant - Masker Rambut Ketombe",
    size: "500 ml",
    price: 1870000,
    concern: "dandruff",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-therapiste-200",
    folder: "masque",
    name: "Kerastase Masque Therapiste - Masker Rambut Rusak",
    size: "200 ml",
    price: 920000,
    concern: "damaged",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-therapiste-500",
    folder: "masque",
    name: "Kerastase Masque Therapiste - Masker Rambut Rusak",
    size: "500 ml",
    price: 1870000,
    concern: "damaged",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-ultra-violet-200",
    folder: "masque",
    name: "Kerastase Masque Ultra Violet - Masker Rambut Dibleaching",
    size: "200 ml",
    price: 920000,
    concern: "colored",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
  {
    id: "m-ultra-violet-500",
    folder: "masque",
    name: "Kerastase Masque Ultra Violet - Masker Rambut Dibleaching",
    size: "500 ml",
    price: 1870000,
    concern: "colored",
    desc: "",
    benefits: [""],
    howToUse: [""],
  },
];
